spring:
  #配置数据源信息
  datasource:
    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #办公室
    url: jdbc:mysql://192.168.28.150:3306/mybatis_plus?characterEncoding=utf-8&userSSL=false
    #家庭
#    url: jdbc:mysql://192.168.28.150:3306/mybatis_plus?characterEncoding=utf-8&userSSL=false
    username: root
    password: zs123456


#Mybatisplus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #设置全局配置
  global-config:
    db-config:
      #设置表名统一前缀
      table-prefix:
      #设置统一的主键生成策略
      id-type: auto
  #配置类型别名所对应的包
  type-aliases-package: com.atguigu.mybatisplus.pojo
  #扫描通用枚举的包
  type-enums-package: com.atguigu.mybatisplus.enums
